### PR TITLE
Add Restkit to project configuration

### PR DESCRIPTION
**Pull request by christiancompton**
This PR addresses some problems with the project.

- When upgrading to the Watson 1.0 SDK, RestKit was added as its own framework - this adds it automatically to the `.xcproj`
- Cleaning of log/print statements
- Swift 4.2 conversion

### CODE REVIEW

**Comment by christiancompton** [comment]
I'm seeing the app crash shortly after starting - I'll try to investigate the threading, but that may be out of scope for this PR.

**Comment by stevemar** [comment]
This is a good start, thanks for letting us know about the legacy api_key authentication being removed. If you can't figure out why the app crashes we'll re-evaluate if it's an issue with this change or if it's happening in master.

**Comment by christiancompton** [comment]
@stevemart This crash is happening in master.  Back in April, I was attributing this error to the old processor on the iPhone 6S I was using, but I have access to an iPhone X now, and was able to replicate.  Can you have someone investigate this?

**Comment by stevemar** [comment]
@christiancompton thanks for confirming it happens on master. 

@sanjeevghimire can you look into this?

@christiancompton think we should merge your changes anyway or will that just make things harder to debug 🤔 ?

**Comment by christiancompton** [comment]
I am finishing some of the error logging improvements still - should be done shortly.

**Review by stevemar — APPROVED** [review]
thanks!

**Pull request merged**
